### ISSUE TITLE
Tracking progress

### ISSUE THREAD

**Issue by patrickphat** [patrickphat/Information-Extraction-Receipts#7]
Date: 19/03
Task:
- [x] Prepare data: Crop image into batches of text-lines given ground truth coordinates @patrickphatnguyen 
- [x] Train CRNN baseline model: Train a CRNN model with prepared data @patrickphatnguyen 
- [x] Write documentation on loading prepared dataset and labels for OCR task @patrickphatnguyen [here](https://github.com/patrickphatnguyen/Optical-Character-Recognition-KV/blob/master/modules-documentation.md)
